export const GET_MOVIES_BY_NAME_REQUEST = 'GET_MOVIES_BY_NAME_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERR ='GET_MOVIES_ERR';
export const GET_POP_MOVIES = 'GET_POP_MOVIES';
export const SORT_MOVIES = 'SORT_MOVIES';